#############################################################
#
# prod 环境
#
#############################################################
server:
  port: 8081                  # web访问端口 约定为:80

spring:
  datasource:                                   # 数据源相关配置
    # url使用云服务器的内网ip
    url: jdbc:mysql://172.31.87.24:3306/mall-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: admin
    password: admin
